### ISSUE TITLE
Elixir Version

### ISSUE THREAD

**Issue by matiasinsaurralde** [unblevable/T.rex#3]
Hi, I'm interested in playing around with T.rex, it looks wonderful!

I'm getting this message:

```** (Mix) You're trying to run :trex on Elixir v1.2.2 but it has declared in its mix.exs file it supports only Elixir ~> 1.1.1```

Is it safe to use Elixir v1.2.2?

Also it would be nice to have a todo list of features you plan to implement so people can contribute :+1: 

Thanks!

**Comment by unblevable** [comment]
Hi, I just pushed a commit that should let T.rex work for Elixir 1.2.

Beware that the client doesn't really work at all in its current state, there are a lot of edge cases it doesn't yet handle, the architecture is constantly changing, etc. The only parts of the project that can be considered somewhat robust at this point are the bencoding and peer-wire protocol modules.

My end-goal is for the client to have a codebase that other Elixir programmers can look to for ideas on how to build an Elixir/OTP project that's a little more involved than the simple examples found in tutorials. I plan to implement the bare-minimum features that is expected for a BitTorrent client, e.g. seeding/leeching for multiple peers at once.

If you can find a simple-enough `.torrent` file that works (I've had luck using the torrent files for Ubuntu distros), you can test how far I've gotten in `iex`:
```
swarm = Trex.a("some_legal.torrent")
```

Once I make a little more progress, I'll slowly add bits and pieces to the README and maybe even include a section for contributors. In the meantime, thanks for the interest!

860d8ae closes #3
